---
- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory

- name: Copy scripts
  ansible.builtin.copy:
    mode: "0755"
    src: "."
    dest: "{{ ansible_user_dir }}/.local/bin/"

