---
- name: Install
  ansible.builtin.package:
    name:
      - redshift
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/redshift"
    state: directory

- name: Copy redshift.conf
  ansible.builtin.copy:
    src: "redshift.conf"
    dest: "{{ ansible_user_dir }}/.config/redshift/"
