stages:
  - build

build:
  stage: build
  image: archlinux:latest
  before_script:
    - pacman -Syyu --noconfirm
    - pacman -S git --noconfirm
    - git config --global user.name "Bob"
    - git config --global user.email "bob@bob.com"
  script:
    - ./setup.sh
