---
- name: Update package cache
  ansible.builtin.pacman:
    update_cache: yes
  become: yes

- name: Install pacman packages from the list
  ansible.builtin.package:
    name: "{{ lookup('file', 'pacman_packages').split('\n') }}"
    state: present
  become: yes

- name: Install yay packages from the list
  kewlfft.aur.aur:
    name: "{{ lookup('template', 'yay_packages.j2').split('\n') }}"
    state: present
    use: yay
