---
- name: Install
  ansible.builtin.package:
    name:
      - xorg-server
    state: latest
  become: yes

- name: Copy .xinitrc
  ansible.builtin.copy:
    src: ".xinitrc"
    dest: "{{ ansible_user_dir }}/"
