---
- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/bspwm"
    state: directory

- name: Scripts folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/bspwm/scripts"
    state: directory

- name: Lock folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/bspwm/scripts/lock"
    state: directory

- name: Copy bspwmrc
  ansible.builtin.copy:
    mode: "0755"
    src: "bspwmrc"
    dest: "{{ ansible_user_dir }}/.config/bspwm/"

- name: Copy lock script
  ansible.builtin.copy:
    mode: "0755"
    src: "lock.sh"
    dest: "{{ ansible_user_dir }}/.config/bspwm/scripts/lock/"

- name: Copy lock image
  ansible.builtin.copy:
    src: "lock.png"
    dest: "{{ ansible_user_dir }}/.config/bspwm/scripts/lock/"
