---
- name: Ensure .ssh directory
  ansible.builtin.file:
    mode: "0700"
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory

- name: Copy config files
  ansible.builtin.copy:
    mode: preserve
    src: "./"
    dest: "{{ ansible_user_dir }}/.ssh"
