---
- name: Ensure groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - android-sdk
    - docker
    - power
    - pulse
    - pulse-access
    - storage
    - wheel

- name: Add {{ ansible_user_id }} to groups
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: android-sdk,docker,power,pulse,pulse-access,storage,wheel
  become: yes
