---
- name: Create sudoers.d folder
  ansible.builtin.file:
    mode: "0755"
    path: "/etc/sudoers.d"
    state: directory
  become: yes

- name: Copy 10-installer
  ansible.builtin.copy:
    src: "10-installer"
    dest: "/etc/sudoers.d/"
  become: yes
