---
- name: Set default shell
  user:
    name: "{{ ansible_env['USER'] }}"
    shell: /usr/bin/zsh
  become: yes

- name: Copy .zprofile
  ansible.builtin.copy:
    src: .zprofile
    dest: "{{ ansible_user_dir }}/"

- name: Copy .zshrc.linux to .zshrc
  ansible.builtin.copy:
    src: .zshrc.linux
    dest: "{{ ansible_user_dir }}/.zshrc"
