---
- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/sxhkd"
    state: directory

- name: Copy sxhkdrc
  ansible.builtin.copy:
    mode: "0755"
    src: "sxhkdrc"
    dest: "{{ ansible_user_dir }}/.config/sxhkd/"
