shell = "zsh"

[plugins]

[plugins.autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.dracula]
github = 'dracula/zsh'

[plugins.syntax]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.fzf]
github = 'Aloxaf/fzf-tab'
