---
- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

- name: Copy common config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/kitty"
  loop:
    - kitty.conf.common
    - diff.conf
    - dracula.conf
