---
- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

- name: Copy config
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/kitty"
    src: "."
