---
- name: Create config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

- name: Template out kitty.conf
  ansible.builtin.template:
    src: kitty.conf.j2
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"

- name: Copy other config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/kitty"
  loop:
    - diff.conf
    - dracula.conf
