---
- name: Set core.pager
  community.general.git_config:
    name: core.pager
    scope: global
    value: diff-so-fancy | less --tabs=4 -RFX

- name: Set credential.helper
  community.general.git_config:
    name: credential.helper
    scope: global
    value: store

- name: Set init.defaultBranch
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Set pull.rebase
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: true
