---
- name: Copy pacman.conf
  ansible.builtin.copy:
    src: "pacman.conf"
    dest: "/etc/"
  become: yes

- name: Copy mirrorlist
  ansible.builtin.copy:
    src: "mirrorlist"
    dest: "/etc/pacman.d/"
  become: yes

- name: pacman update/upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: yes
