---
- name: Link pacman.conf
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/pacman/files/pacman.conf"
    dest: "/etc/pacman.conf"
    state: link
    force: true
  become: yes

- name: Link mirrorlist
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/pacman/files/mirrorlist"
    dest: "/etc/pacman.d/mirrorlist"
    state: link
    force: true
  become: yes

- name: pacman update/upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: yes
