---
- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/rofi"
    state: directory

- name: Copy config.rasi
  ansible.builtin.copy:
    src: "config.rasi"
    dest: "{{ ansible_user_dir }}/.config/rofi/"
