---
- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/ghostty"
    state: directory

- name: Template ghostty config
  ansible.builtin.template:
    src: config.j2
    dest: "{{ ansible_user_dir }}/.config/ghostty/config"

