---
- name: Install
  ansible.builtin.package:
    name:
      - tmux
    state: latest
  become: yes

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/tmux"
    state: directory

- name: Copy config
  ansible.builtin.copy:
    src: "tmux.conf"
    dest: "{{ ansible_user_dir }}/.config/tmux/"
