---
- name: Link .gtkrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/appearance/files/settings.ini"
    dest: "{{ ansible_user_dir }}/.config/gtk-3.0/settings.ini"
    state: link
    force: true
