---
- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Copy init.lua
  ansible.builtin.copy:
    src: "init.lua"
    dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"

- name: Copy modules
  ansible.builtin.copy:
    src: "lua/"
    dest: "{{ ansible_user_dir }}/.config/nvim/lua"

- name: Copy ftplugin
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/nvim/ftplugin"
    src: "ftplugin/"
